events {}

http {
  upstream simulation_api {
    server simulation-api:8080;
  }

  upstream webhook_ingest {
    server webhook-ingest:8080;
  }

  server {
    listen 80;

    location /simulation-scenarios {
      proxy_pass http://simulation_api;
      proxy_set_header X-Correlation-Id $http_x_correlation_id;
      proxy_set_header X-Api-Key $http_x_api_key;
    }

    location /webhooks/crossriver/lending {
      proxy_pass http://webhook_ingest;
      proxy_set_header X-Correlation-Id $http_x_correlation_id;
      proxy_set_header X-Api-Key $http_x_api_key;
    }

    location /health {
      proxy_pass http://simulation_api;
    }
  }
}
